version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:16.14.0
    steps:
      - checkout
      - run: npm install
      - npm: npm start
      - run: npm test
      - run: npm run build
workflows:
  build_test:
    jobs:
      - run_test
