version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/node:16.14.0
    steps:
      - checkout
      - run: 
          npm install
          npm start
          npm test
          npm run build

