version: 2.1
orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2

jobs:
  run_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run unit tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  - cypress/run:
      name: Run Cypress tests
      requires:
        - run_test
      record: true
      parallel: true
      parallelism: 2
      start: npm start
      wait-on: 'http://localhost:5500'
      spec: cypress/e2e/*.spec.js

workflows:
  build_test:
    jobs:
      - run_test
