version: 1.0
jobs:
  build:
    docker:
      - image: circleci/node:16.14.0
    steps:
      - checkout
      - run: npm install
      - npm: npm start
      - run: npm test
      - run: npm run build
workflows:
  version: 1
  build:
    jobs:
      - build
